version: '3.9'
name: factum

services:
  app:
    image: ${DOCKER_IMAGE_NAME}:${APP_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-production
    restart: always
    environment:
      PORT: ${PORT}
      PG_HOST: postgres
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: postgres-production
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - postgres_data_production:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${PG_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_production:
